# Generated by Django 4.2.10 on 2024-02-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="link",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="post",
            name="date_modified",
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
