# Generated by Django 4.2.10 on 2024-02-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_post_content_alter_post_date_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
