# Generated by Django 4.2.10 on 2024-02-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_post_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
